 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: {{APP_NAME}}
   namespace: {{NAMESPACE}}
 spec:
   tls:
   - hosts:
     - {{APP_NAME}}.{{CLUSTER_HOST}}
   rules:
   - host: {{APP_NAME}}.{{CLUSTER_HOST}}
     http:
       paths:
       - backend:
           service:
             name: {{APP_NAME}}
             port:
               number: 80
         path: /
         pathType: Prefix
